version: '3.8'

services:
  api:
    build: .
    ports:
      - "3001:3000"
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=api_vendas
      # For security, do NOT keep secrets in this file. Provide JWT_SECRET and JWT_EXPIRES_IN
      # via host environment variables or a .env file loaded by docker-compose.
      # Example (host):
      #   export JWT_SECRET=your_generated_secret
      #   export JWT_EXPIRES_IN=1d
      # docker-compose will pass those values to the container when starting.
    depends_on:
      - postgres
    networks:
      - app-network

  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: api_vendas
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8081:80"
    depends_on:
      - postgres
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
