@baseUrl = http://localhost:3000
@authToken = {{authToken}}

### Categories
POST {{baseUrl}}/categories
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "name": "Eletrônicos",
  "description": "Produtos eletrônicos"
}

###
PUT {{baseUrl}}/categories/1
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "name": "Informática",
  "description": "Produtos de informática"
}

###
PATCH {{baseUrl}}/categories/1
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "description": "Equipamentos de informática"
}

###
DELETE {{baseUrl}}/categories/1
Authorization: Bearer {{authToken}}
