@baseUrl = http://localhost:3001
@authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhNTU0ZGFiZS1jOTliLTRiNmItOGE3Ny1mYmYwNTcxOWExZGEiLCJlbWFpbCI6InZpbmljaXVzQGVtYWlsLmNvbSIsImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE3NjEyNTk3MzEsImV4cCI6MTc2MTM0NjEzMX0.jonoHXCkSPoUc402d6bQiC-apocBZBx2I8qsNdo1IAI
@clientUuid = 3db6f6d0-6884-44fd-bd8d-eae787db0c31

### Clients
POST {{baseUrl}}/clients
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "name": "João da Fazenda",
  "document": "12345678901",
  "email": "joao@fazenda.com",
  "phone": "+55 11 99999-9999",
  "address": {
    "street": "Estrada Rural São João",
    "number": "123",
    "city": "Ribeirão Preto",
    "state": "SP",
    "postalCode": "14000-000",
    "country": "BR"
  }
}

###
GET {{baseUrl}}/clients
Authorization: Bearer {{authToken}}

###
GET {{baseUrl}}/clients/{{clientUuid}}
Authorization: Bearer {{authToken}}

###
PUT {{baseUrl}}/clients/{{clientUuid}}
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "name": "João Santos da Fazenda",
  "document": "12345678901",
  "email": "joao.santos@fazenda.com",
  "address": {
    "street": "Rodovia Anhanguera",
    "number": "456",
    "city": "Ribeirão Preto",
    "state": "SP",
    "postalCode": "14020-000",
    "country": "BR"
  }
}

###
PATCH {{baseUrl}}/clients/{{clientUuid}}
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "email": "joao.novo@fazenda.com"
}

###
DELETE {{baseUrl}}/clients/{{clientUuid}}
Authorization: Bearer {{authToken}}
