@baseUrl = http://localhost:3001
@authToken = {{AUTH_TOKEN}}

### Products
POST {{baseUrl}}/products
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "name": "Notebook Dell",
  "ean": "7891234567890",
  "price": 2500.00,
  "description": "Notebook Dell Inspiron",
  "categoryId": 1,
  "brandId": null
}

###
PUT {{baseUrl}}/products/1
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "name": "Notebook Dell XPS",
  "ean": "7891234567890",
  "price": 3500.00,
  "description": "Notebook Dell XPS 13",
  "categoryId": 1
}

###
PATCH {{baseUrl}}/products/1
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "price": 3000.00
}

###
DELETE {{baseUrl}}/products/1
Authorization: Bearer {{authToken}}
