@baseUrl = http://localhost:3001
@authToken = {{AUTH_TOKEN}}

### Sales
POST {{baseUrl}}/sales
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "value": 2500.00,
  "discount": 100.00,
  "productId": 1,
  "clientId": 1
}

###
PUT {{baseUrl}}/sales/1
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "value": 3000.00,
  "discount": 200.00,
  "productId": 1,
  "clientId": 1
}

###
PATCH {{baseUrl}}/sales/1
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "discount": 150.00
}

###
DELETE {{baseUrl}}/sales/1
Authorization: Bearer {{authToken}}
