@baseUrl = http://localhost:3001
@authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhNTU0ZGFiZS1jOTliLTRiNmItOGE3Ny1mYmYwNTcxOWExZGEiLCJlbWFpbCI6InZpbmljaXVzQGVtYWlsLmNvbSIsImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE3NjEyNTk3MzEsImV4cCI6MTc2MTM0NjEzMX0.jonoHXCkSPoUc402d6bQiC-apocBZBx2I8qsNdo1IAI

### Auth - Login (define {{authToken}})
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "vinicius@email.com",
  "password": "123456"
}

### Users
POST {{baseUrl}}/users
Content-Type: application/json

{
  "name": "Vinicius Franco",
  "email": "vinicius@email.com",
  "admin": false,
  "password": "123456"
}

###
GET {{baseUrl}}/users
Authorization: Bearer {{authToken}}

###
GET {{baseUrl}}/users/{{userUuid}}
Authorization: Bearer {{authToken}}

###
PUT {{baseUrl}}/users/{{userUuid}}
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "name": "João Santos",
  "email": "joao.santos@email.com",
  "admin": true,
  "password": "newpass"
}

###
PATCH {{baseUrl}}/users/{{userUuid}}
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "name": "Vinicius Franco "
}

###
DELETE {{baseUrl}}/users/{{userUuid}}
Authorization: Bearer {{authToken}}
