@baseUrl = http://localhost:3001
@authToken = {{authToken}}

### Users
POST {{baseUrl}}/users
Content-Type: application/json

{
  "name": "João Silva",
  "email": "joao@email.com",
  "admin": false,
  "password": "123456"
}

###
PUT {{baseUrl}}/users/1
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "name": "João Santos",
  "email": "joao.santos@email.com",
  "admin": true,
  "password": "newpass"
}

###
PATCH {{baseUrl}}/users/1
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "admin": true
}

###
DELETE {{baseUrl}}/users/1
Authorization: Bearer {{authToken}}
